### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by lucyllewy**
Signed-off-by: Dani Llewellyn <diddledani@ubuntu.com>

### CODE REVIEW

**Review by merlijn-sebrechts — APPROVED** [review]
LGTM!

**Comment by lucyllewy** [comment]
Thanks :-)

**Comment by ghost** [comment]
It reads Ubuntu community, shouldn't it read Snapcrafters community?

**Comment by lucyllewy** [comment]
it's a copy+pasta of the Ubuntu Community CoC, so...

**Comment by ghost** [comment]
Overall, it looks good, but it would be great to change all of the instances Ubuntu -> Snapcrafters (as you did with the title).

**Pull request merged**
